"""add_ics_generated

Revision ID: 5cf6d5bcfda7
Revises: e000c20ac637
Create Date: 2026-08-05 20:43:14.126385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf6d5bcfda7'
down_revision: Union[str, Sequence[str], None] = 'e000c20ac637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS calendar_sync_time TIMESTAMP WITH TIME ZONE")
    op.execute("ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS ics_generated BOOLEAN DEFAULT false NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE leave_requests DROP COLUMN IF EXISTS ics_generated")
    op.execute("ALTER TABLE leave_requests DROP COLUMN IF EXISTS calendar_sync_time")
    # ### end Alembic commands ###
