"""Phase 6 models

Revision ID: a031801f3ba6
Revises: 7b193aba91ba
Create Date: 2026-08-03 17:01:48.067723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a031801f3ba6'
down_revision: Union[str, Sequence[str], None] = '7b193aba91ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_policies',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_policies_id'), 'company_policies', ['id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('leave_type_id', sa.BigInteger(), nullable=False),
    sa.Column('calendar_year', sa.Integer(), nullable=False),
    sa.Column('eligible', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('available', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pending', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_id'), 'leave_balances', ['id'], unique=False)
    op.create_index(op.f('ix_leave_balances_leave_type_id'), 'leave_balances', ['leave_type_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('leave_type_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('half_day', sa.Boolean(), nullable=False),
    sa.Column('half_day_session', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('hr_id', sa.BigInteger(), nullable=True),
    sa.Column('reference_code', sa.String(length=100), nullable=False),
    sa.Column('applied_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('hr_comments', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['hr_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_index(op.f('ix_leave_requests_reference_code'), 'leave_requests', ['reference_code'], unique=True)
    op.create_table('policy_acceptances',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('policy_id', sa.BigInteger(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['company_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_acceptances_employee_id'), 'policy_acceptances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_policy_acceptances_id'), 'policy_acceptances', ['id'], unique=False)
    op.create_index(op.f('ix_policy_acceptances_policy_id'), 'policy_acceptances', ['policy_id'], unique=False)
    op.add_column('employees', sa.Column('hr_eligibility_approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'hr_eligibility_approved')
    op.drop_index(op.f('ix_policy_acceptances_policy_id'), table_name='policy_acceptances')
    op.drop_index(op.f('ix_policy_acceptances_id'), table_name='policy_acceptances')
    op.drop_index(op.f('ix_policy_acceptances_employee_id'), table_name='policy_acceptances')
    op.drop_table('policy_acceptances')
    op.drop_index(op.f('ix_leave_requests_reference_code'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_leave_balances_leave_type_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_company_policies_id'), table_name='company_policies')
    op.drop_table('company_policies')
    # ### end Alembic commands ###
