"""Phase 7 manager fields

Revision ID: da5a12e78469
Revises: a031801f3ba6
Create Date: 2026-08-03 17:07:15.114576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5a12e78469'
down_revision: Union[str, Sequence[str], None] = 'a031801f3ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('submitted_on_behalf', sa.Boolean(), nullable=False))
    op.add_column('leave_requests', sa.Column('submitted_by_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'leave_requests', 'employees', ['submitted_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_column('leave_requests', 'submitted_by_id')
    op.drop_column('leave_requests', 'submitted_on_behalf')
    # ### end Alembic commands ###
