"""add_calendar_sync

Revision ID: e000c20ac637
Revises: dd7b8f7e2412
Create Date: 2026-08-05 18:14:58.889628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e000c20ac637'
down_revision: Union[str, Sequence[str], None] = 'dd7b8f7e2412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True))
    op.add_column('leave_requests', sa.Column('outlook_calendar_event_id', sa.String(length=255), nullable=True))
    op.add_column('leave_requests', sa.Column('calendar_provider', sa.String(length=50), nullable=True))
    op.add_column('leave_requests', sa.Column('calendar_synced', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('leave_requests', sa.Column('calendar_sync_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leave_requests', sa.Column('ics_generated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'ics_generated')
    op.drop_column('leave_requests', 'calendar_sync_time')
    op.drop_column('leave_requests', 'calendar_synced')
    op.drop_column('leave_requests', 'calendar_provider')
    op.drop_column('leave_requests', 'outlook_calendar_event_id')
    op.drop_column('leave_requests', 'google_calendar_event_id')
    # ### end Alembic commands ###
